# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c97c98d3e586302d2b3f18a80aa008d28e54af9127baf4a76c4ffee0efded6cddcd0b8868178f6b52e2f5a0b136a62411a2d61f61266483178c21bd27b53ec25

test:
  secret_key_base: 32d08cb8859717bca8ce82dcd4a6e8245f8918ff15668ea77f590a8aaaac14e8d2c48084a8a3a40a3eb1d265fdb8d59b159847b56ee1eaa070880252631e16b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
